using UnityEngine;

public class LPOO : MonoBehaviour
{
    //5 EXERCICIOS
    //TODOS A SAIDA DO PROGRAMA É PELO PRINT
    //TODOS OS EXERCICIOS TEM QUE ESTAR DENTRO DESSE SCRIPTY
    //TESTAR OS METODOS NA CLASSE LPOO 
    //UTILIZAR O ARQUIIVO LEMBRETE.TXT PARA REVISÃO
    //UTILIZAR RACIOCIONIO LOGIO PARA SABER QUANDO USAR AS FERRAMENTAS NO ARQUIVO TXT
    //REOLVER OS EXERCICIOS USANDO SUA LOGIA DE PROGRAMAÇÃO


    // 1- FAÇA UMA CLASSE CHAMADA CALCULADORA COM OS METODOS SOMA SUBTRAÇÃO DIVIÇÃO E MULTPLICAÇÃO

    // 2- FAÇA UMA METODO NA CLASSE CALCULLADORA QUE SAIDA É TODAS AS TABUADAS

    // 3- FAÇA UMA CLASSE CHAMADA PESSOA COM OS SEGUINTES ATRIBUTOS, NOME, IDADE, PESO, ALTURA, GENERO

    // 4- FAÇA UMA METODO NA CLASSE PESSOA PARA CALCULAR O IMC DE PESSOA 

    // 5- FAÇA UMA METODO PARA SABER IDADE ATUAL DA PESSOA

    // DESAFIO - FAÇA UMA FUÇÃO NA CLASSE CALCULADORA PARA CALCULAR O FATORIAL DE UM NUMERO



}

